#spring:
 # application:
  #  name: order-service
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#            defaultZone: http://localhost:8761/eureka/
#            instance:
#                  hostname: localhost


#spring:
#  zipkin:
#    base-url: http://localhost:9411/